name: Numeric Jungle
url: 'https://numericjungle.github.io'
description: ""

exclude: [Gemfile, Gemfile.lock, README.md]
markdown: kramdown

author: 'Sean Chang'

gems:
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed

excerpt_separator: "<!--excerpt-->"


