name: Numeric Jungle
url: 'https://numericjungle.github.io'
description: ""

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

author: 'Sean C'

plugins:
  - jekyll-gist
  - jekyll-sitemap

sass:
    sass_dir: _sass
    style: :compressed

excerpt_separator: "<!--excerpt-->"


